pipeline{
    agent{
        node{
         label 'AGENT-1'
        }
    }

    options{
        timeout(time:'1', unit:'Hours')
        disableConcurrentBuilds()
    }

    stages{
        stage('Init'){
            steps{
                sh """
                cd 01-vpc
                terraform init -reconfigure
                """
            }
        }
        stage('Plan'){
            steps{
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        stage('Apply'){
            input{
                message "should we continue..?"
                ok "U can continue..."
            }
            steps{
                sh """
                cd 01-vpc
                terraform apply -auto-approve
                """
            }
        }
        stage('Destroy'){
            input{
                message "should we continue..?"
                ok "U can continue..."
            }
            steps{
                sh """
                cd 01-vpc
                terraform destroy -auto-approve
                """
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello Again'
        }
        failure{
            echo 'I will say Hello only if pipeline is Failed'
        }
        success{
            echo 'I will say Hello only if pipeline is Successfull'
        }
    }
}