pipeline {
    //agent any                     // -------------> default agent
//agent which is created by us here we r declaring
    agent {
      node{
        label 'AGENT-1'
      }
    }
  
   options{
        // timeout(time:1, unit:'HOURS')
        // disableConcurrentBuilds()
        ansiColor('xterm')
    }
    //  parameters {
    //     choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    // }
    stages {
        stage('Init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
        
         stage('Plan') {
            steps {
               sh """
                    cd 01-vpc
                    terraform plan 
                """
            }
        }
         stage('Apply') {
            input{
                message "should we continue?"
                ok "yes, U can.."
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure { 
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success{
            echo 'I will say Hello when pipeline is success'
        }
    }



}
