pipeline{
    agent{
        node{
            label 'Agent-1'
        }
    }

    options{
        timeout(time:1, unit:'HOURS')
        disableConcurrentBuilds()
    }

    stages{
        stage('Init'){
            steps{
                sh """
                cd 01-vpc
                terraform init -reconfigure
                """
            }
        }
        stage('plan'){
            steps{
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        stage('apply'){
            steps{
                sh """
                cd 01-vpc
                terraform apply -auto-approve
                """
            }
        }
        stage('destroy'){
            steps{
                sh """
                cd 01-vpc
                terraform destroy -auto-approve
                """
            }
        }
    }
    post{
        always{
            echo 'I will say Hello always'
        }
        failure{
            echo 'I will say not Hello only if pipeline is Failed'
        }
        success{
            echo 'I will say Hello only if pipeline is Successfull'
        }
    }
}